# Dependencies
markdown:         kramdown
#gems:             [jekyll-paginate]

# Permalinks
permalink:        pretty

# Setup
title:            Chaojie's Blog
tagline:          ''
description:      ''
url:              'https://www.cjackie.net'
baseurl:          '/blog/'
paginate:         5

author:
  name:           'Chaojie Wang'

# Custom vars
version:          1.0.0

github:           https://github.com/cjackie
