# Dependencies
markdown:         kramdown

# Permalinks
permalink:        pretty

# Setup
title:            Chaojie's Blog
tagline:          'Keep learning'
description:      'There should be no boundaries to human endeavor.'
url:              http://cjackie.github.com
baseurl:          '/'
paginate:         3

author:
  name:           'Chaojie Wang'
  url:            https://www.linkedin.com/pub/chaojie-wang/6b/a7a/290

# Custom vars
version:          1.0.0

github:           https://github.com/cjackie
